import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      // The homepage is a pixel-exact port from the app repo: plain <img> tags
      // and literal apostrophes in copy that the compliance tests assert on.
      "@next/next/no-img-element": "off",
      "react/no-unescaped-entities": "off",
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // The Civic Modern design system export: a vendored reference copy of the
    // owner's Claude Design system, committed so the tokens and component
    // prompts are readable next to the code that implements them. Nothing in
    // it is imported, built, or shipped - the shipped form of the system is
    // the `--mh-*` token block in MarketingHomepage.css.
    //
    // It is generated by another tool and lints as third-party code would:
    // three errors (a setState in an effect, a React 17 `ReactDOM.render`, an
    // assignment to `module`) and twenty-two warnings, none of them ours to
    // fix, since editing the export would only be undone by the next one.
    // Those three errors had `npm run lint` - and therefore CI's
    // `test-and-build` job - failing on `main` and on every branch since the
    // directory was added in 3f96385, which meant a red check carried no
    // information and got ignored. Ignoring the vendored copy is what makes
    // the job mean something again.
    "docs/design-system-civic-modern/**",
  ]),
]);

export default eslintConfig;
